###服务端口号
server:
  port: 8100
###eureka 基本信息配置
spring:
  application:
    name: eureka-server
eureka:
  instance:
    ###注册到eurekaip地址
    hostname: 127.0.0.1
  #    hostname: 172.21.0.13
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    ###因为自己是为注册中心，不需要自己注册自己
    #      defaultZone: http://127.0.0.1:8009/eureka/
    register-with-eureka: false
    ###因为自己是为注册中心，不需要检索服务
    fetch-registry: false

  server:
    # 测试时关闭自我保护机制，保证不可用服务及时踢出
    enable-self-preservation: false
    # 每隔两秒检测一次
    eviction-interval-timer-in-ms: 2000
